import json
from pathlib import Path
p=Path('/mnt/data/pypath_work/src/data/lessons.json')
data=json.loads(p.read_text())
info={
'l01':[['Created by','Guido van Rossum'],['Started / first published','Early 1990s; Python 0.9.0 appeared in 1991'],['Origin','CWI (Stichting Mathematisch Centrum), Netherlands'],['Why the name?','Inspired by Monty Python’s Flying Circus'],['Used for','Web development, data/science, AI, education, software development, automation, and more']],
'l02':[['Core idea','A variable name refers to a value'],['Assignment','Use = to bind a name to a value'],['Reassignment','A name can later refer to a different value'],['Example','score = 10 → score = 20'],['Important','Assignment is not the same as comparison (==)']],
'l03':[['Common types','int, float, str, bool, None'],['Check a type','Use type(value)'],['Convert','int(), float(), str(), bool() can convert values when appropriate'],['Important','Input from input() is text'],['Tip','Convert at the boundary when you know the expected type']],
'l04':[['Strings','Text values written with quotes'],['Indexing','Characters use zero-based positions'],['Slicing','text[start:stop] selects part of a string'],['Useful methods','strip(), lower(), upper(), replace(), split()'],['Tip','Strings are immutable; string methods return new strings']],
'l05':[['input()','Reads text typed by the user'],['Return type','input() always returns a str'],['Conversion','Use int() or float() when numeric input is needed'],['Cleaning','strip() removes surrounding whitespace'],['Common use','Interactive programs, menus, calculators, and forms']],
'l06':[['Arithmetic','+, -, *, /, //, %, **'],['Comparison','==, !=, <, >, <=, >='],['Boolean','and, or, not combine or invert conditions'],['Result','Comparisons produce True or False'],['Tip','Use parentheses when a condition needs clearer grouping']],
'l07':[['if','Runs code when a condition is true'],['elif','Checks another condition if earlier ones were false'],['else','Provides the fallback branch'],['Indentation','The indented block belongs to the condition'],['Common use','Validation, decisions, permissions, and program flow']],
'l08':[['for','Iterates through items in a sequence or iterable'],['while','Repeats while a condition remains true'],['range()','Commonly used for counted loops'],['Loop variable','Receives the current item/value each iteration'],['Tip','Make sure loops have a clear stopping condition']],
'l09':[['break','Stops the current loop'],['continue','Skips to the next iteration'],['Accumulator','A variable can keep a running total/count'],['Problem solving','Define what repeats, what changes, and when it ends'],['Tip','Prefer a clear loop condition over hidden control flow']],
'l10':[['Function','A reusable block of code with a defined purpose'],['Parameters','Names that receive values when the function is called'],['return','Sends a result back to the caller'],['Arguments','Actual values passed into a function'],['Good practice','Keep functions focused on one clear job']],
'l11':[['List','Ordered, mutable collection'],['Tuple','Ordered, immutable collection'],['Indexing','Both use zero-based indexing'],['Unpacking','Assign multiple values from an iterable'],['Use case','Lists for changing collections; tuples for fixed grouped values']],
'l12':[['Dictionary','Stores key-value pairs'],['Set','Stores unique values without duplicate entries'],['Lookup','dict[key] retrieves a value by key'],['Membership','Use in to check keys or set membership'],['Use case','Dictionaries model named data; sets help with uniqueness']],
'l13':[['Comprehension','Compact syntax for building collections'],['Pattern','[expression for item in iterable]'],['Filtering','A condition can be added with if'],['Best practice','Understand the normal loop before shortening it'],['Avoid','Do not force complex logic into one comprehension']],
'l14':[['Module','A Python file that can be imported'],['import','Loads names from another module'],['Standard library','Python includes many ready-to-use modules'],['Common examples','math, random, pathlib, json, datetime'],['Good practice','Keep imports clear and avoid unnecessary wildcard imports']],
'l15':[['File handling','Lets programs save and read information'],['with open()','Safely manages opening and closing files'],['JSON','A common text format for structured data'],['json module','json.load()/loads() read; json.dump()/dumps() write'],['Tip','Validate data before trusting file contents']],
'l16':[['SyntaxError','Python cannot parse the code'],['TypeError','An operation received an inappropriate type'],['ValueError','A value has the right type but an invalid value'],['Debugging','Read the traceback, identify the line, then isolate the cause'],['Best habit','Change one thing and run the smallest useful test']],
'l17':[['Purpose','Tests verify that code behaves as expected'],['Assertion','assert checks an expected condition'],['Unit test','Tests a small piece of behavior'],['Good coverage','Test normal, boundary, and invalid cases'],['Benefit','Tests make refactoring safer']],
'l18':[['Class','Defines the structure and behavior of objects'],['Object','An instance created from a class'],['self','Refers to the current instance'],['dataclass','A concise way to define data-focused classes'],['Tip','Use classes when grouping related state and behavior adds clarity']],
'l19':[['Composition','Build objects by giving them other objects'],['Inheritance','Create a class based on another class'],['Prefer composition','Often simpler when behavior needs to be combined'],['super()','Access behavior from a parent class'],['Design goal','Use relationships that make the program easier to understand']],
'l20':[['Iterator','An object that produces values one at a time'],['iter()','Gets an iterator from an iterable'],['next()','Requests the next value'],['Generator','A convenient way to create lazy iterators'],['yield','Produces a value while preserving generator state']],
'l21':[['Decorator','Wraps a function/class to add behavior'],['@syntax','Applies a decorator to the definition below it'],['Context manager','Controls setup and cleanup around a block'],['with','Common syntax for using a context manager'],['Caution','Understand the underlying function first; these are advanced tools']],
'l22':[['Type hints','Describe intended types without changing normal Python semantics'],['Example','def add(a: int, b: int) -> int:'],['Documentation','Docstrings explain what code does and how to use it'],['Tools','Type checkers and editors can use annotations'],['Best practice','Keep annotations accurate and useful rather than decorative']],
'l23':[['HTTP','A protocol commonly used for web communication'],['Request','A client sends a method such as GET or POST'],['Response','A server returns a status, headers, and often data'],['JSON','A common format for API request/response data'],['Runtime','Browser network access may differ from local Python']],
'l24':[['SQLite','A lightweight file-based relational database'],['SQL','Language used to query and change relational data'],['Core operations','SELECT, INSERT, UPDATE, DELETE'],['Python','The sqlite3 module provides database access in standard Python'],['Runtime','PyPath browser support may differ from a full local Python installation']],
'l25':[['asyncio','Python’s standard library for asynchronous programming'],['async def','Defines a coroutine function'],['await','Pauses a coroutine until an awaitable completes'],['Best for','I/O-bound work such as network or other waiting tasks'],['Important','Async code is not automatically faster for CPU-heavy work']],
'l26':[['Logging','Structured runtime information for diagnosing programs'],['Levels','DEBUG, INFO, WARNING, ERROR, CRITICAL'],['Configuration','Keep settings separate from core program logic'],['Security','Never casually log passwords, tokens, or other secrets'],['Benefit','Good logs help explain what happened without stopping the program']],
'l27':[['CLI','Command-line interface for running programs with commands/options'],['Git','Version control for tracking code history'],['Core Git','status, add, commit, log, branch, switch, pull, push'],['Packaging','Defines how Python projects are organized and installed'],['Professional habit','Commit small meaningful changes with clear messages']],
'l28':[['Architecture','The high-level structure and responsibilities of a program'],['Refactoring','Improve internal code structure without changing intended behavior'],['Separation','Keep responsibilities in focused modules/functions'],['Duplication','Repeated logic is often a refactoring signal'],['Goal','Make change easier, not simply make the project larger']],
'l29':[['Performance','How efficiently a program uses time and resources'],['First step','Measure before optimizing'],['Common tools','timeit and profiling help find slow areas'],['Big impact','Better algorithms often matter more than micro-optimizations'],['Rule','Keep optimization changes readable and evidence-based']],
'l30':[['Goal','Turn a specification into a complete, maintainable Python application'],['Required skills','Planning, functions, validation, persistence, testing, and debugging'],['Quality check','Normal, boundary, and invalid cases should be tested'],['Documentation','Explain installation, usage, and important design choices'],['Outcome','A strong Python foundation—not mastery of every Python specialization']],
}
for x in data:
    if x['kind']=='lesson':
        x['quickInfo']=info[x['id']]
        x.pop('teachingPoints',None)
    elif x['kind']=='project':
        # Projects do not need the removed lesson-only Key Points field either.
        x.pop('teachingPoints',None)
p.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
