import json
from pathlib import Path

root=Path('/tmp/pypath')
p=root/'src/data/lessons.json'
data=json.loads(p.read_text())
by={x['id']:x for x in data}

# Ordered 30-lesson curriculum: beginner foundations -> application building -> professional Python.
meta = [
('l01','Programs & Output','Programming starts with instructions. Python executes statements in order, so learning to read that flow is the first step toward controlling a program.','Understand how a Python program executes instructions from top to bottom.','A program is a set of instructions that a computer follows. Python reads executable statements in sequence unless another construct changes the flow.','Start with the smallest possible program: print a message, inspect the output, then change one line and run it again.',['Read a Python statement as an instruction.','Use print() to display information.','Run code and compare the result with what you expected.','Recognize that order matters.'],[('1. Read: Each statement gives Python an instruction.','print("Hello")'),('2. Execute: Python normally starts at the first executable line.','print("A")\nprint("B")'),('3. Observe: Output is evidence of what the program did.','print(2 + 3)  # 5'),('4. Experiment: Change one small thing and rerun.','print("Python")\n# change the word and run again')],
[('Do not start with a large program.','Start with a tiny runnable example.','print("First program")'),('Do not guess what code did without running it.','Make a prediction, then verify it.','print(10 - 3)  # predict 7')],
'Print your name, your favorite number, and the result of 7 + 5 on separate lines.',
[('Guided','Change the existing print statements to show three pieces of information about you.'),('Independent','Write a four-line introduction program using only print().'),('Challenge','Make the output look like a small profile card using multiple print() calls.')],
[
('What does Python normally do first?',['Execute the first executable statement','Skip to the last line','Run only comments','Choose a random line'],0,'Python normally executes statements in order.'),
('What does print() do?',['Displays a value or message','Creates a loop','Defines a function','Deletes a variable'],0,'print() sends a representation of its arguments to the program output.'),
('What is the output?',['A then B','B then A','AB on one line only','Nothing'],0,'The two print statements execute in order.'),
('What is the best first debugging step for a tiny program?',['Run it and inspect the actual result','Rewrite the whole program','Ignore the output','Add advanced syntax'],0,'Running the smallest reproducible example gives you evidence.'),
('Which habit helps you learn programming fastest?',['Predict, run, observe, and change one thing','Copy large solutions','Avoid experiments','Memorize every function'],0,'Small experiments turn syntax into understanding.')]),
('l02','Variables & Assignment','Programs need a way to remember information. Variables give names to values so those values can be used and changed later.','Learn names, values, assignment, rebinding, and clear variable naming.','Assignment associates a name with a value. A name can later be rebound to another value.','Use variables to make your programs readable and to keep important values available for later steps.',['Explain assignment as naming a value.','Create and reassign variables.','Choose descriptive names.','Understand that variables do not permanently own a type.'],[('1. Assign: Put a value behind a name.','score = 10'),('2. Rebind: The same name can refer to a new value.','score = 10\nscore = 20'),('3. Read: Use the name to retrieve the current value.','print(score)'),('4. Name clearly: Good names communicate purpose.','total_price = 25.50')],
[('Do not use vague names for important values.','Prefer names that explain the value.','total_price = 25'),('Do not assume assignment means equality in mathematics.','Think “name now refers to this value.”','x = x + 1')],
'Create variables for a product name, price, and quantity, then calculate and print the total.',
[('Guided','Create name, price, and quantity variables and print each one.'),('Independent','Calculate a shopping total from price and quantity variables.'),('Challenge','Add a second product and calculate the combined total.')],
[
('What does assignment do?',['Associates a name with a value','Compares two values','Repeats code','Imports a module'],0,'Assignment gives a name a current value.'),
('After this code, what is x?',['7','3','10','Error'],0,'The second assignment rebinds x to 7.'),
('Why is total_price better than x for a price?',['It communicates the value’s purpose','It runs faster','It is required by Python','It prevents reassignment'],0,'Descriptive names make code easier to read.'),
('Can a variable be rebound?',['Yes','No','Only once','Only if it is a string'],0,'Python names can be rebound to new values.'),
('What does x = x + 1 mean in Python?',['Read x, add 1, then assign the result back to x','It checks whether x equals x + 1','It creates a constant','It is invalid Python'],0,'The right side is evaluated before the result is assigned to x.')]),
('l03','Data Types & Conversion','Python values have different types, and input often arrives as text. Understanding types and conversion prevents many beginner errors.','Understand int, float, str, bool, None, and safe basic conversion.','A type describes what kind of value you have and which operations make sense for it.','Learn to inspect a value with type(), recognize strings versus numbers, and convert input when the program genuinely needs another type.',['Recognize common built-in types.','Use type() to inspect a value.','Convert strings to numbers when appropriate.','Understand None as the absence of a value.'],[('1. Inspect: Ask Python what type a value has.','type(42)  # int'),('2. Convert: Turn compatible text into a number.','age = int("20")'),('3. Check: A string that looks numeric is still text until converted.','"20" + "5"  # "205"'),('4. Recognize None: It represents no current value.','result = None')],
[('Do not add numbers to strings by accident.','Convert input before arithmetic.','age = int(input("Age: "))'),('Do not compare None as if it were a normal number.','Use is None when checking for no value.','if result is None:')],
'Ask for a person’s age and height, convert the inputs to useful numeric types, and print both values.',
[('Guided','Inspect the types of 10, 2.5, "10", True, and None.'),('Independent','Ask for two numbers, convert them, and print their sum.'),('Challenge','Handle a non-numeric age with try/except and explain the error to the user.')],
[
('What type is 42?',['int','str','float','bool'],0,'42 is an integer.'),
('What type does input() return by default?',['str','int','float','bool'],0,'input() returns text, even when the user types digits.'),
('What does int("12") produce?',['The integer 12','The string "12"','The float 12.0','None'],0,'int() converts compatible text to an integer.'),
('How should you check whether result contains no value?',['result is None','result == 0','type(result) == str','result > None'],0,'None is best checked with identity using is None.'),
('Why can "2" + "3" produce "23"?',['Both values are strings and + concatenates them','Python converts them to floats','The values are booleans','It is an error'],0,'String + joins strings together.')]),
('l04','Strings','Text is everywhere in real programs: names, messages, files, commands, and API data. Strings become much easier once you understand indexing, methods, formatting, and immutability.','Work confidently with strings, indexing, slicing, common methods, and f-strings.','A string is an immutable sequence of characters. Python provides methods and formatting tools for transforming and presenting text.','Practice reading and transforming text rather than memorizing a long list of string methods.',['Index and slice strings.','Use common methods such as strip(), lower(), and split().','Build readable messages with f-strings.','Know that string operations create new strings rather than changing the original.'],[('1. Index: Access one character by position.','word = "Python"\nprint(word[0])'),('2. Slice: Select part of a string.','word[0:3]  # "Pyt"'),('3. Clean: Normalize user input.','name = input().strip().lower()'),('4. Format: Put values into readable text.','f"Hello, {name}"')],
[('Do not manually concatenate long messages.','Use f-strings for values inside text.','f"Total: {total}"'),('Do not expect strip() to change the original string.','Assign the returned string when needed.','name = name.strip()')],
'Ask for a name, clean the input, and print a friendly greeting using an f-string.',
[('Guided','Use strip() and lower() on a sample name.'),('Independent','Ask for a full name and print it in a consistent format.'),('Challenge','Extract the first name from a two-word input and build a personalized message.')],
[
('What does word[0] return for "Python"?',['P','y','Python','n'],0,'Index 0 is the first character.'),
('What does strip() mainly do?',['Removes surrounding whitespace','Converts text to an integer','Splits every character','Changes the original string in place'],0,'strip() returns a new string without surrounding whitespace.'),
('Which is an f-string?',['f"Hello, {name}"','"Hello, {name}"','format(name, Hello)','string(name)'],0,'An f-string evaluates expressions inside braces.'),
('Are strings mutable?',['No','Yes, always','Only numbers are mutable','Only empty strings are mutable'],0,'String operations return new strings.'),
('What is "Py" from "Python"[0:2]?',['Py','Pyt','ython','Python'],0,'The stop index is excluded.')]),
('l05','Input & Type Conversion','Interactive programs get information from users. The most important beginner detail is that input arrives as text and must be converted when arithmetic or another type-specific operation is needed.','Build small interactive programs with input(), validation, and conversion.','input() reads a line of user text and returns it as a string. Conversion functions create values of other types when the input is valid.','Treat user input as untrusted data: read it, normalize it, validate it, then use it.',['Read input with input().','Convert numeric text with int() or float().','Use strip() to clean simple text input.','Recognize invalid input as a normal case to handle.'],[('1. Read: input() returns text.','raw = input("Age: ")'),('2. Clean: Remove accidental spaces.','name = raw.strip()'),('3. Convert: Turn compatible text into a number.','age = int(raw)'),('4. Validate: Check whether a value makes sense.','if age < 0:')],
[('Do not trust input to already have the right type.','Convert and validate it.','age = int(input("Age: "))'),('Do not let one invalid value crash the whole interaction.','Use try/except around conversions when needed.','try:\n    age = int(raw)\nexcept ValueError:')],
'Build an age checker that accepts a whole-number age and rejects invalid or negative input.',
[('Guided','Read a name and age, convert the age, and print both.'),('Independent','Build a simple positive-number checker.'),('Challenge','Create a menu that keeps asking until the user enters a valid choice.')],
[
('What does input() return?',['A string','An integer','A boolean','A list'],0,'User input is returned as text.'),
('Why use int(input(...))?',['To convert numeric text into an integer','To print the input','To remove spaces only','To create a list'],0,'int() converts compatible numeric text to an integer.'),
('Which error can invalid int conversion raise?',['ValueError','KeyError','IndexError','ImportError'],0,'int("hello") raises ValueError.'),
('What should a robust input flow do?',['Read, clean, validate, then use the value','Assume everything is valid','Ignore errors','Convert every value to a string'],0,'Validation belongs between reading input and using it.'),
('What is a good way to handle repeated invalid input?',['Keep asking until the input is valid','Crash immediately','Silently accept any value','Delete the program'],0,'Loops are useful for retrying invalid input.')]),
('l06','Operators & Boolean Logic','Operators let programs calculate, compare, and combine conditions. Boolean logic is the foundation of every decision your programs make.','Use arithmetic, comparison, membership, and boolean operators accurately.','Operators combine or transform values. Comparisons produce True or False, which can be combined with and, or, and not.','Learn to read an expression before trying to memorize operator precedence. Use parentheses when they make intent clearer.',['Use arithmetic operators.','Compare values with ==, !=, <, >, <=, >=.','Combine conditions with and/or/not.','Use in and not in for membership.'],[('1. Calculate: Arithmetic operators produce numeric results.','total = price * quantity'),('2. Compare: Comparisons produce booleans.','age >= 18'),('3. Combine: and requires both conditions.','is_member and paid'),('4. Membership: Check whether a value is present.','"admin" in roles')],
[('Do not use = when you mean comparison.','Use == for equality checks.','if score == 100:'),('Do not write deeply nested boolean expressions without need.','Use clear intermediate variables or parentheses.','can_enter = paid and not banned')],
'Write a small eligibility checker using arithmetic, comparisons, and at least one and/or condition.',
[('Guided','Predict the results of five comparison expressions.'),('Independent','Build an eligibility check using age and membership status.'),('Challenge','Combine three conditions into a readable access rule and explain it in plain English.')],
[
('Which operator checks equality?',['==','=','=>','!='],0,'== compares two values; = performs assignment.'),
('What does 5 > 3 evaluate to?',['True','False','5','3'],0,'The comparison is true.'),
('What does A and B require?',['Both A and B must be true','Only A must be true','Neither can be true','A must be false'],0,'and requires both operands to be truthy.'),
('What does not True produce?',['False','True','None','0'],0,'not reverses a boolean value.'),
('What does "py" in "python" return?',['True','False','py','python'],0,'The substring is present, so membership is true.')]),
('l07','Conditions','Programs become useful when they can make decisions. Conditions let your code choose different actions based on data.','Write clear if/elif/else decisions and combine them with validated input.','A conditional executes different branches depending on whether an expression is true or false.','Start with one decision, then add branches only when the problem actually needs them.',['Write if/elif/else blocks.','Indent branches correctly.','Order overlapping conditions carefully.','Keep complex decisions readable.'],[('1. Check: Evaluate the condition.','if age >= 18:'),('2. Branch: Run the matching indented block.','if score >= 50:\n    print("Pass")'),('3. Add alternatives: Use elif for additional cases.','if score >= 90:\n    grade = "A"\nelif score >= 80:\n    grade = "B"'),('4. Fallback: else handles remaining cases.','else:\n    grade = "Needs work"')],
[('Do not put unrelated work inside every branch.','Calculate shared values before the decision when possible.','total = price * quantity\nif total > 100: ...'),('Do not assume elif checks all branches.','Python stops at the first matching branch.','if score >= 90: ...\nelif score >= 80: ...')],
'Build a grade checker that converts a numeric score into A, B, C, D, or F.',
[('Guided','Write an if/else that checks whether a number is positive.'),('Independent','Build the grade checker using ordered elif branches.'),('Challenge','Add validation so scores outside 0–100 are rejected before grading.')],
[
('When does an if block run?',['When its condition is true','Always','Only when false','Only after a loop'],0,'The if body runs when its condition evaluates to true.'),
('What does elif provide?',['Another condition checked if earlier branches did not match','A loop','A function parameter','A comment'],0,'elif adds another mutually exclusive branch.'),
('Which score should be checked first for grades?',['The highest threshold','The lowest threshold','A random threshold','Only zero'],0,'Higher thresholds must be checked before lower overlapping thresholds.'),
('What does else handle?',['Cases not matched by earlier branches','Only errors','Only true values','Loop repetition'],0,'else is the fallback branch.'),
('What is the best way to handle an impossible score?',['Validate it before grading','Treat it as A','Ignore it','Convert it to a string'],0,'Validation prevents invalid data from entering the grading logic.')]),
('l08','Loops','Programs often need to repeat work. Loops let you process collections, retry input, and repeat actions without duplicating code.','Use for and while loops safely, with clear loop conditions and useful state.','A loop repeats a block of code. for is ideal for iterating over items; while repeats while a condition remains true.','Choose the loop based on the problem: iterate over known items with for, or repeat until a condition changes with while.',['Loop over strings and collections.','Use range() for counted repetition.','Use while for condition-driven repetition.','Update loop state so while loops can terminate.'],[('1. Iterate: for visits each item.','for name in names:\n    print(name)'),('2. Count: range() produces a sequence of integers.','for number in range(5):'),('3. Repeat: while continues while its condition is true.','while attempts < 3:'),('4. Progress: Change the state that controls while.','attempts += 1')],
[('Do not use while without a clear exit path.','Identify what changes the condition.','while attempts < 3: attempts += 1'),('Do not manually repeat the same statement many times.','Use a loop for repeated work.','for _ in range(5):\n    print("Hello")')],
'Print the numbers 1–10, then build a loop that keeps asking for a password until it is correct.',
[('Guided','Use for and range() to print 1–5.'),('Independent','Calculate the sum of numbers from 1 to 100 with a loop.'),('Challenge','Build a retry loop with a maximum of three attempts and a clear failure message.')],
[
('Which loop is natural for each item in a list?',['for','while only','if','try'],0,'for iterates over items directly.'),
('What does range(3) produce for a loop?',['0, 1, 2','1, 2, 3','0, 1, 2, 3','Only 3'],0,'The stop value is excluded.'),
('What must a while loop have to avoid an accidental infinite loop?',['A condition that can eventually become false','A list','A function','A print statement'],0,'The loop needs a path toward termination.'),
('What is the cleanest way to process every name in names?',['for name in names:','for i in range(1000):','while True:','if names:'],0,'Iterating over the collection directly is clearest.'),
('Why use a loop for repeated work?',['It avoids duplicated code and scales with the data','It always runs faster','It removes all errors','It makes every program asynchronous'],0,'Loops express repetition without copy-pasting.')]),
('l09','Loop Control & Problem Solving','Real programs need to stop, skip, and accumulate work inside loops. This lesson also starts deliberate problem-solving: break a task into steps before coding.','Use break, continue, counters, accumulators, and a simple plan before writing the loop.','Loop control changes the current iteration. A counter or accumulator keeps useful state while the loop runs.','Before writing a loop, identify the input, the repeated action, the state you need, and the stopping condition.',['Use break to stop a loop when a goal is reached.','Use continue to skip the current iteration.','Build counters and accumulators.','Plan a loop in plain language first.'],[('1. Plan: State what repeats and what ends it.','“Read values until q, count valid entries.”'),('2. Accumulate: Update a running result.','total += amount'),('3. Skip: continue moves to the next iteration.','if value < 0:\n    continue'),('4. Stop: break exits the loop.','if command == "q":\n    break')],
[('Do not use break to hide a poorly designed condition.','Give the loop a clear purpose and exit rule.','while True:\n    command = input()\n    if command == "q": break'),('Do not update counters in unrelated places.','Keep state changes close to the event they count.','attempts += 1')],
'Build a command loop that accepts numbers, counts valid entries, totals them, and stops when the user enters q.',
[('Guided','Count how many even numbers appear in a small list.'),('Independent','Build a loop that sums positive values until q is entered.'),('Challenge','Create a small menu loop with add, view, and quit commands.')],
[
('What does break do?',['Exits the current loop','Skips only one iteration','Restarts the loop','Ends Python permanently'],0,'break exits the nearest loop.'),
('What does continue do?',['Skips to the next iteration','Ends the loop','Adds one to a counter','Returns from a function'],0,'continue moves to the next iteration.'),
('What is an accumulator?',['A variable that builds a result over iterations','A loop condition','A type of error','A module'],0,'An accumulator stores a running result such as a total.'),
('What should you identify before coding a loop?',['Repeated action, state, and stopping condition','Only variable names','Only the final print','Nothing'],0,'Planning the loop behavior reduces trial-and-error.'),
('Which is a good reason to use a menu loop?',['The program needs repeated user commands','The program has no input','Only one statement exists','It makes code shorter automatically'],0,'Menu programs naturally repeat until the user quits.')]),
('l10','Functions','Functions turn a program into reusable, testable pieces. They are one of the biggest steps from writing scripts to designing programs.','Define functions, pass arguments, return values, and keep responsibilities small.','A function packages a behavior under a name. Parameters receive inputs and return sends a result back to the caller.','Prefer functions that do one clear job and return useful results instead of hiding everything inside print statements.',['Define and call functions.','Distinguish parameters from arguments.','Return values and store them.','Keep functions focused and reusable.'],[('1. Define: Describe the function once.','def add(a, b):\n    return a + b'),('2. Call: Run the function with arguments.','result = add(2, 3)'),('3. Return: Send a value back to the caller.','return total'),('4. Reuse: Call the same function from different places.','print(add(1, 2))\nprint(add(5, 6))')],
[('Do not make every function print instead of returning data.','Return values when callers may need them.','def add(a, b): return a + b'),('Do not write giant functions that do unrelated jobs.','Split distinct responsibilities into functions.','load_data(); validate(data); save_data(data)')],
'Write a function calculate_total(price, quantity) that returns the total instead of printing it.',
[('Guided','Write a function that returns the square of a number.'),('Independent','Create functions for add, subtract, multiply, and divide.'),('Challenge','Build a small calculator by composing reusable functions and handling division by zero.')],
[
('What does return do?',['Sends a value back to the caller','Prints text only','Repeats a function','Imports code'],0,'return gives the caller a result and exits the current function.'),
('In def add(a, b), what are a and b?',['Parameters','Arguments','Return values','Modules'],0,'Parameters are names defined by the function signature.'),
('Why return a value instead of only printing it?',['The caller can use the result in other operations','return is always faster','Printing is invalid','It prevents testing'],0,'Returned values are reusable by the caller.'),
('What is a good function responsibility?',['One clear job','Every feature in the program','Only printing','Only input'],0,'Small focused functions are easier to understand and test.'),
('What happens when a function reaches return?',['It exits that function and gives the result back','It restarts','It continues after return','It closes Python'],0,'Execution leaves the current function at return.')]),
('l11','Lists, Tuples & Unpacking','Collections let programs work with groups of values. Lists are mutable, tuples are immutable, and unpacking gives names to items cleanly.','Create, index, modify, iterate, and unpack sequence data.','A list is a mutable ordered collection. A tuple is an immutable ordered collection. Both support indexing and iteration.','Choose the collection based on whether the data should change and whether the structure itself should stay fixed.',['Create and modify lists.','Index and slice sequences.','Use append, remove, and sort appropriately.','Unpack tuples into meaningful names.'],[('1. Store: Put related values together.','names = ["Ava", "Ben", "Cara"]'),('2. Index: Access an item by position.','names[0]'),('3. Modify: Lists can change.','names.append("Dan")'),('4. Unpack: Assign tuple items to names.','point = (3, 4)\nx, y = point')],
[('Do not copy a list just to read it.','Iterate over its items directly.','for name in names: print(name)'),('Do not use a tuple when you need to mutate the sequence repeatedly.','Use a list for changing collections.','tasks = []')],
'Create a shopping list, add three items, remove one, and print the final list with positions.',
[('Guided','Create a list of three foods and print each item.'),('Independent','Build a small shopping-list program with add/remove behavior.'),('Challenge','Unpack a three-value tuple and use the names in a formatted report.')],
[
('Which collection is mutable?',['list','tuple','str','int'],0,'Lists can be changed after creation.'),
('What does names.append("Dan") do?',['Adds Dan to the end of the list','Removes Dan','Sorts the list','Creates a tuple'],0,'append adds one item to the end.'),
('What does x, y = (3, 4) do?',['Unpacks the two values into x and y','Adds them','Creates a list','Converts them to strings'],0,'Unpacking assigns sequence items to names.'),
('What is the first index of a sequence?',['0','1','-1','None'],0,'Python sequences are zero-indexed.'),
('When is a tuple useful?',['When the sequence structure should not be changed','When you need frequent append','When storing only text','Only for loops'],0,'Tuples are immutable sequences.')]),
('l12','Dictionaries & Sets','Most real programs need named data and fast membership checks. Dictionaries and sets solve different problems than lists.','Use dictionaries for key-value data and sets for unique membership.','A dictionary maps keys to values. A set stores unique values and is useful for membership and removing duplicates.','Think about the question your data structure should answer: “what value belongs to this key?” suggests a dictionary; “have I seen this?” often suggests a set.',['Create, read, update, and iterate dictionaries.','Use get() when a key may be missing.','Create sets and remove duplicates.','Use membership checks clearly.'],[('1. Map: Associate a key with a value.','user = {"name": "Ava", "age": 20}'),('2. Read: Access a known key.','user["name"]'),('3. Safe read: Provide a fallback.','user.get("email", "not provided")'),('4. Unique: A set removes duplicates.','unique = set([1, 1, 2, 3])')],
[('Do not assume every dictionary key exists.','Use get() when absence is expected.','email = user.get("email")'),('Do not use a list when your main question is membership.','Consider a set for unique membership.','seen = {"alice", "bob"}')],
'Build a contact lookup dictionary and a set of unique cities, then demonstrate a safe lookup and membership check.',
[('Guided','Create a dictionary with name and age and read both values.'),('Independent','Build a small contact lookup by username.'),('Challenge','Track unique tags with a set and report whether a requested tag exists.')],
[
('What does a dictionary store?',['Key-value pairs','Only ordered numbers','Only unique values','Functions only'],0,'Dictionaries map keys to values.'),
('What does user.get("email") help with?',['Reading a possibly missing key without a KeyError','Sorting the dictionary','Deleting email','Creating a set'],0,'get() can return None or a fallback when the key is absent.'),
('What is a set useful for?',['Unique values and membership checks','Keeping duplicate order','Key-value mapping','Formatted text'],0,'Sets store unique elements.'),
('What happens with set([1,1,2])?',['It contains 1 and 2','It contains two 1s','It raises a syntax error','It becomes a dictionary'],0,'Sets remove duplicates.'),
('Which is best for looking up a user by username?',['Dictionary','Set','Tuple only','String'],0,'A dictionary maps usernames to user data.')]),
('l13','Comprehensions','Comprehensions are a concise way to build collections from existing iterables. They are useful after you understand the normal loop they replace.','Convert simple collection-building loops into readable list, set, and dictionary comprehensions.','A comprehension expresses “build a new collection from these items, optionally filtering them” in one expression.','Always understand the loop first. Use a comprehension when it remains clearer than the multi-line version.',['Translate a simple loop into a list comprehension.','Add a condition to filter values.','Recognize set and dictionary comprehensions.','Avoid dense nested comprehensions.'],[('1. Start with the loop: Build the result normally.','squares = []\nfor n in numbers:\n    squares.append(n * n)'),('2. Compress: Express the same transformation.','squares = [n * n for n in numbers]'),('3. Filter: Add an if condition.','evens = [n for n in numbers if n % 2 == 0]'),('4. Choose clarity: Keep a normal loop when the logic is complex.','for item in items:\n    ...')],
[('Do not use comprehensions just to look clever.','Prefer the clearer form.','result = [n * 2 for n in numbers]'),('Do not cram several nested decisions into one line.','Use a normal loop for complex logic.','for item in items:\n    if valid(item): ...')],
'Convert a loop that builds squared even numbers into a list comprehension, then compare both versions.',
[('Guided','Turn a simple “append doubled value” loop into a comprehension.'),('Independent','Create a comprehension containing only positive numbers.'),('Challenge','Build a dictionary comprehension mapping words to their lengths.')],
[
('What should you understand before writing a comprehension?',['The equivalent normal loop','Only the brackets','Nothing','Only set syntax'],0,'The normal loop makes the transformation and filtering logic explicit.'),
('What does [n * 2 for n in numbers] do?',['Builds a list with each number doubled','Filters all numbers','Creates a dictionary','Sorts numbers'],0,'It transforms each item and collects the results.'),
('Where does a comprehension condition go?',['After the iterable expression','Before the brackets','Inside the variable name','After the list is printed'],0,'A filtering if clause follows the iterable.'),
('When should you prefer a normal loop?',['When the logic becomes complex or harder to read','Always','Never','Only with strings'],0,'Readability is more important than shortening code.'),
('What can a dictionary comprehension build?',['A dictionary from key/value expressions','Only a list','Only a set','Only a tuple'],0,'Dictionary comprehensions use key:value expressions.')]),
('l14','Modules & Imports','Real programs are split into files so code can be reused and understood. Modules also introduce the standard library, which prevents reinventing common tools.','Import your own modules and standard-library modules, and keep module responsibilities clear.','A module is a Python file that can be imported. Imports make functions, classes, and values from other modules available to your program.','Learn how to find and reuse standard-library functionality before writing your own version.',['Import a module.','Import selected names deliberately.','Create a small reusable module.','Understand the purpose of if __name__ == "__main__".'],[('1. Import: Load a module.','import math\nprint(math.sqrt(25))'),('2. Select: Import a specific name when clear.','from pathlib import Path'),('3. Reuse: Put related functions in a module.','from helpers import format_name'),('4. Main guard: Run demo code only when the file is executed directly.','if __name__ == "__main__":\n    main()')],
[('Do not duplicate utility functions across files.','Move reusable behavior into a module.','from helpers import format_name'),('Do not use wildcard imports in beginner projects.','Import the module or named functions explicitly.','import math')],
'Create a small helper module with a greeting function and import it into a main program.',
[('Guided','Import math and use one function from it.'),('Independent','Create helpers.py with one reusable function and import it.'),('Challenge','Split a small calculator into a main module and a math helper module.')],
[
('What is a module?',['A Python file that can be imported','A loop','A variable only','A database'],0,'A .py file can act as an importable module.'),
('Why use modules?',['To organize and reuse code','To make every program asynchronous','To avoid functions','Only for comments'],0,'Modules separate responsibilities and enable reuse.'),
('What does import math do?',['Makes the math module available','Runs every program on the computer','Creates a variable called sqrt','Deletes math'],0,'The module becomes available under the name math.'),
('Why use the main guard?',['To prevent demo/main code from running on import','To speed up loops','To create classes','To validate JSON'],0,'The guard distinguishes direct execution from import.'),
('Which import is explicit?',['from pathlib import Path','from pathlib import *','import everything','load pathlib'],0,'The explicit import names exactly what is being used.')]),
('l15','Files & JSON','Programs become useful when they can remember information after they close. Files and JSON provide a simple path from in-memory data to persistent data.','Read and write text files and JSON safely, including missing or invalid data.','A file stores data outside the running program. JSON represents common Python data structures in a portable text format.','Keep file paths deliberate, handle missing files, and treat malformed data as a case your program should recover from.',['Read and write text files.','Use pathlib for paths.','Serialize data with json.','Handle missing or malformed data.'],[('1. Path: Represent a file path clearly.','from pathlib import Path\nFILE = Path("data.json")'),('2. Read: Load text from a file.','text = FILE.read_text(encoding="utf-8")'),('3. Parse: Convert JSON text to Python data.','data = json.loads(text)'),('4. Save: Convert Python data back to JSON.','FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")')],
[('Do not assume the file already exists.','Check or handle FileNotFoundError.','if not FILE.exists(): return []'),('Do not crash on malformed JSON in a user data file.','Catch JSONDecodeError and choose a safe fallback.','except json.JSONDecodeError: return []')],
'Build a tiny JSON-backed notes store that loads notes, adds one note, and saves them again.',
[('Guided','Write a text file and read it back.'),('Independent','Save a list of names as JSON and load it again.'),('Challenge','Build a JSON notes file that recovers gracefully when the file is missing or malformed.')],
[
('What does json.loads() do?',['Parses JSON text into Python data','Writes a file','Deletes JSON','Creates a database'],0,'loads parses a JSON string into Python objects.'),
('What does json.dumps() do?',['Converts Python data to JSON text','Reads a file','Creates a class','Runs a loop'],0,'dumps serializes Python data as JSON text.'),
('Why use pathlib.Path?',['It provides clear path and file operations','It makes Python asynchronous','It replaces JSON','It is only for web APIs'],0,'Path provides convenient cross-platform path operations.'),
('What should happen if a JSON file is malformed?',['Handle the parse error and choose a safe recovery','Pretend it is valid','Delete Python','Always crash'],0,'User data can be invalid, so recovery is part of robust code.'),
('Why does persistence matter?',['Data survives after the program closes','It makes loops faster','It prevents all errors','It removes functions'],0,'Files let information survive the current process.')]),
('l16','Errors & Debugging','Errors are normal in programming. The goal is not to avoid every error but to read evidence, isolate the problem, make one useful change, and verify the fix.','Read tracebacks, distinguish common error types, use try/except appropriately, and debug systematically.','A traceback identifies where an exception occurred and what went wrong. Exception handling lets a program recover from expected failures.','Debug from evidence rather than guessing. Reproduce the smallest failure you can and change one thing at a time.',['Read the bottom of a traceback first.','Recognize SyntaxError, TypeError, ValueError, KeyError, and IndexError.','Use try/except around expected failures.','Debug with small reproducible examples.'],[('1. Locate: Find the file and line named by the traceback.','ValueError: invalid literal for int()'),('2. Identify: Read the exception type and message.','TypeError: unsupported operand type(s)'),('3. Fix: Change the smallest relevant piece.','age = int(raw)  # after validation'),('4. Verify: Rerun the same failing case.','Use the same input to confirm the fix.')],
[('Do not catch every exception blindly.','Catch expected exceptions and preserve useful errors.','except ValueError:'),('Do not rewrite the whole program after one bug.','Isolate the failing line and make one change.','print(type(value), value)')],
'Debug a short program with three intentional bugs: a bad conversion, a missing dictionary key, and an invalid list index.',
[('Guided','Read a traceback and identify its file, line, and exception type.'),('Independent','Fix three intentional exceptions without rewriting the program.'),('Challenge','Build an input loop that recovers from invalid numbers and explains the problem.')],
[
('Where is the most useful summary of an exception usually shown?',['Near the bottom of the traceback','Only in the first line','In the browser address bar','Nowhere'],0,'The final lines normally show the exception type and message.'),
('Which error fits int("hello")?',['ValueError','KeyError','IndexError','NameError'],0,'The value cannot be converted to an integer.'),
('What is a good debugging change?',['One small evidence-based change','Many unrelated edits','Delete the failing feature','Ignore the traceback'],0,'Small changes make cause and effect easier to see.'),
('When is try/except appropriate?',['When a failure is expected and the program can recover','For every line','Only for syntax errors','Never'],0,'Exception handling is useful around expected runtime failures.'),
('What should you do after fixing a bug?',['Rerun the failing case and verify the behavior','Assume it works','Remove all tests','Change another random line'],0,'Reproducing the failure after the fix confirms the result.')]),
('l17','Testing','Testing turns “it seems to work” into evidence. Good tests cover normal behavior, boundaries, and invalid cases, especially for functions that return values.','Write small assertions and use pytest-style thinking even when running simple checks in PyPath.','A test checks that actual behavior matches an expected result. Good tests make failures specific and repeatable.','Start with pure functions because they are easy to test, then add tests around file and user-input boundaries.',['Write focused assertions.','Test normal and edge cases.','Use descriptive test names.','Separate behavior from user-interface code when possible.'],[('1. Arrange: Prepare a known input.','numbers = [2, 4]'),('2. Act: Call the function.','result = total(numbers)'),('3. Assert: State the expected behavior.','assert result == 6'),('4. Expand: Add edge cases.','assert total([]) == 0')],
[('Do not test only the happy path.','Include empty, boundary, and invalid cases.','assert parse_age("20") == 20'),('Do not make one test prove ten unrelated behaviors.','Keep each test focused.','assert add(2, 3) == 5')],
'Write three assertions for a function that converts a temperature from Celsius to Fahrenheit, including one edge case.',
[('Guided','Write assertions for add(2, 3) and add(-1, 1).'),('Independent','Create a function and at least three tests for it.'),('Challenge','Test a function that validates user input, including invalid and boundary values.')],
[
('What does an assertion do?',['Checks an expected condition and fails when it is false','Prints every variable','Creates a loop','Imports pytest'],0,'An assertion makes expected behavior explicit.'),
('What should good tests include?',['Normal, boundary, and invalid cases where relevant','Only one successful case','Only random data','No edge cases'],0,'Different cases expose different classes of bugs.'),
('Why are pure functions easy to test?',['They return predictable results from their inputs','They never have parameters','They always use files','They cannot fail'],0,'Pure behavior has fewer external dependencies.'),
('What is a focused test?',['One clear behavior or expectation','The entire application at once','Only visual output','A random code sample'],0,'Focused tests make failures easier to understand.'),
('What should a failing test tell you?',['Which expected behavior did not occur','Nothing useful','That Python is broken','Only that the program is slow'],0,'A good test localizes a behavior mismatch.')]),
('l18','Classes & Dataclasses','Classes model data and behavior together when that makes a program clearer. Dataclasses remove boilerplate for simple data-oriented objects.','Create simple classes, use attributes and methods, and choose dataclasses for structured records.','A class defines a custom type. An instance is an object created from that class. A dataclass can generate common initialization and representation code for data-focused objects.','Use classes when an object has meaningful state and behavior; do not create a class merely because Python allows it.',['Define classes and __init__.','Use instance attributes and methods.','Create objects from classes.','Use @dataclass for simple records.'],[('1. Define: Describe the object type.','class Task:\n    def __init__(self, title):\n        self.title = title'),('2. Instantiate: Create an object.','task = Task("Study")'),('3. Behave: Put related behavior on the class when useful.','def rename(self, title):\n    self.title = title'),('4. Simplify data: Use dataclass for record-like objects.','@dataclass\nclass User:\n    name: str')],
[('Do not create classes for every tiny value.','Use a class when state and behavior belong together.','class Task: ...'),('Do not expose unnecessary internal state.','Give objects small, clear interfaces.','task.rename("Review")')],
'Create a Task dataclass with title and done fields, then write a function that marks a task complete.',
[('Guided','Create a dataclass with two fields and print an instance.'),('Independent','Build Task objects and a function that marks one complete.'),('Challenge','Add validation and a method that produces a readable task summary.')],
[
('What is an instance?',['An object created from a class','A module','A function parameter','A loop'],0,'An instance is a concrete object of a class.'),
('What does self refer to?',['The current instance','The class file','The next object','A global variable'],0,'self refers to the current object instance.'),
('Why use @dataclass?',['To reduce boilerplate for data-focused classes','To make code asynchronous','To replace all functions','To create databases'],0,'Dataclasses generate common methods for record-like classes.'),
('When should you avoid a class?',['When simple functions or data structures are clearer','Always','Only in scripts','Only with strings'],0,'Classes should solve a design problem, not add ceremony.'),
('Where does instance state usually live?',['On the instance as attributes','Only in comments','Only in imports','In the Python interpreter name list'],0,'Instance attributes store object-specific state.')]),
('l19','Composition & Inheritance','Once you use classes, you need to decide how objects relate. Composition is often the simpler default; inheritance is useful when one type genuinely specializes another.','Compare composition and inheritance and choose the simpler relationship for a design.','Composition builds objects from other objects. Inheritance creates a subtype that reuses or extends a base class.','Prefer relationships that make responsibilities obvious. Inheritance should express a real “is-a” relationship, not merely share code.',['Build objects that contain other objects.','Recognize a genuine is-a relationship.','Override methods carefully.','Prefer composition when inheritance adds unnecessary coupling.'],[('1. Compose: Give one object another object.','class Report:\n    def __init__(self, formatter):\n        self.formatter = formatter'),('2. Inherit: Specialize a base type.','class Admin(User):\n    ...'),('3. Override: Change behavior deliberately.','def describe(self):\n    return "Admin"'),('4. Choose: Ask whether the relationship is truly “is-a”.','Car is a Vehicle; Car has an Engine')],
[('Do not use inheritance only to reuse two lines.','Use composition or a helper when that is clearer.','report = Report(formatter)'),('Do not build deep inheritance trees.','Keep hierarchies shallow and meaningful.','class Admin(User): ...')],
'Design a small notification system using composition: a service should receive a notifier object rather than inherit from it.',
[('Guided','Identify whether five example relationships are “has-a” or “is-a”.'),('Independent','Build a small composition example with two objects.'),('Challenge','Compare a composition and inheritance design for the same problem and choose one.')],
[
('What does composition mean?',['One object contains or uses another object','Every class inherits from one base','A loop contains a class','A function imports itself'],0,'Composition connects objects by giving one object another object to use.'),
('When is inheritance appropriate?',['When the subtype genuinely is a specialized form of the base type','Whenever two classes share a method','Always','Only for dataclasses'],0,'Inheritance communicates an is-a relationship.'),
('What is often the safer default?',['Composition','Deep inheritance','Global variables','Copy-paste'],0,'Composition usually keeps relationships more flexible.'),
('What is method overriding?',['A subclass provides its own implementation of inherited behavior','Deleting a method','Calling a method twice','Renaming a variable'],0,'A subclass can override inherited behavior.'),
('Why avoid deep inheritance trees?',['They increase coupling and make behavior harder to reason about','They are slower to type','Python forbids them','They remove all reuse'],0,'Deep hierarchies make changes harder to understand.')]),
('l20','Iterators & Generators','Iterators and generators are useful when data should be processed one item at a time. They are powerful, but they are an advanced tool rather than a beginner requirement.','Understand iteration, iter(), next(), yield, and lazy processing without overusing them.','An iterator produces values one at a time. A generator function uses yield to create an iterator lazily.','Use generators when you genuinely want lazy processing or streaming behavior; a normal list is often clearer for small data.',['Explain iterable versus iterator.','Use iter() and next() at a basic level.','Write a simple generator with yield.','Recognize when a list is simpler.'],[('1. Iterable: A value can provide an iterator.','numbers = [1, 2, 3]'),('2. Iterator: next() retrieves one item.','it = iter(numbers)\nnext(it)'),('3. Yield: A generator pauses and resumes.','def countdown(n):\n    while n:\n        yield n\n        n -= 1'),('4. Choose: Lazy data is useful for large or streamed inputs.','for value in countdown(3): ...')],
[('Do not use generators just to look advanced.','Use them when lazy processing has a benefit.','yield value'),('Do not call next() blindly without considering exhaustion.','Iterate with for when manual control is unnecessary.','for item in iterator: ...')],
'Create a generator that yields the first N even numbers and consume it with a for loop.',
[('Guided','Use iter() and next() on a three-item list.'),('Independent','Write a generator that yields squares from 1 to N.'),('Challenge','Explain why the generator uses less immediate memory than building the full list.')],
[
('What does yield do?',['Produces a value from a generator and pauses it','Ends Python','Creates a list immediately','Imports a module'],0,'yield produces one value and resumes later.'),
('What is an iterator?',['An object that produces values one at a time','Only a list','A type of error','A class decorator'],0,'Iterators provide successive values.'),
('Why can generators save memory?',['They produce values lazily instead of storing them all at once','They compress Python','They delete values','They avoid loops'],0,'Only the current value needs to be produced.'),
('When is a list simpler?',['When the dataset is small and immediate access is useful','Never','Only with strings','Only with databases'],0,'Not every sequence benefits from lazy evaluation.'),
('What happens when an iterator is exhausted?',['next() raises StopIteration','It starts over automatically','It becomes a list','It returns every value again'],0,'StopIteration signals the end of an iterator.')]),
('l21','Decorators & Context Managers','Decorators and context managers are advanced Python tools that solve recurring problems such as wrapping behavior and guaranteeing cleanup. They should be understood after functions are comfortable.','Understand the purpose and basic shape of decorators and with statements.','A decorator wraps a callable to add behavior. A context manager controls setup and cleanup around a with block.','Focus on what these tools accomplish before worrying about their implementation details.',['Explain a decorator at a high level.','Recognize @decorator syntax.','Use with for managed resources.','Understand why cleanup should be reliable.'],[('1. Wrap: A decorator receives a function and returns a wrapped function.','def logged(func): ...'),('2. Apply: @logged changes how the function is used.','@logged\ndef save(): ...'),('3. Manage: with establishes a controlled resource scope.','with open("notes.txt") as file: ...'),('4. Clean up: Context managers guarantee cleanup when leaving the block.','with resource():\n    use(resource)')],
[('Do not write a decorator before you understand the function it wraps.','Start from the plain function and add one behavior.','@logged\ndef save(): ...'),('Do not manually manage resources when with already expresses the lifecycle.','Use context managers for files and similar resources.','with open(path) as file: ...')],
'Use a with block to read a text file, then inspect a simple decorator example that logs when a function is called.',
[('Guided','Use with open(...) to read a small file.'),('Independent','Write a decorator that prints “calling” before a function runs.'),('Challenge','Explain what cleanup a context manager protects you from forgetting.')],
[
('What does a decorator generally do?',['Wraps a callable to add behavior','Creates a database','Repeats a loop','Converts strings'],0,'Decorators add behavior around a callable.'),
('What does @logged mean above a function?',['Apply the logged decorator to that function','Call the function immediately','Create a variable','Open a file'],0,'The @ syntax applies a decorator.'),
('Why use with open(...) as file?',['It manages the file resource and closes it reliably','It makes the file global','It converts text to JSON','It disables errors'],0,'The context manager handles cleanup.'),
('Are decorators a beginner requirement?',['No, they are an advanced technique built on functions','Yes, before variables','Only for loops','Only for SQL'],0,'They become useful after core function concepts are solid.'),
('What is the key idea of a context manager?',['Set up a resource, use it, and reliably clean it up','Repeat a function','Create a class automatically','Sort a file'],0,'Context managers define a managed resource lifecycle.')]),
('l22','Type Hints & Documentation','Professional Python code should communicate intent to humans and tools. Type hints and documentation improve readability without changing Python into a statically typed language.','Add useful type hints, docstrings, and clear function documentation.','Type hints annotate expected types; Python generally does not enforce them at runtime. Docstrings explain what a module, function, or class does.','Use hints where they clarify an interface, not as decoration on every trivial expression.',['Annotate function parameters and returns.','Use common collection type hints.','Write short useful docstrings.','Keep names and documentation consistent.'],[('1. Annotate: State expected types.','def add(a: int, b: int) -> int:'),('2. Document: Explain behavior and constraints.','def divide(a: float, b: float) -> float:\n    """Return a divided by b."""'),('3. Read: Type hints help readers and tools.','names: list[str] = []'),('4. Verify: Runtime validation is still needed when inputs are untrusted.','if not isinstance(value, int): ...')],
[('Do not claim type hints validate runtime input automatically.','Validate external data separately.','age: int = int(raw)'),('Do not write huge docstrings for obvious code.','Document behavior, inputs, outputs, and important constraints.','"""Return the total price including tax."""')],
'Add type hints and a concise docstring to a function that calculates an order total.',
[('Guided','Annotate a function with parameter and return types.'),('Independent','Document a small utility with a useful docstring.'),('Challenge','Add type hints to a mini module and identify where runtime validation is still required.')],
[
('What do type hints primarily provide?',['Information for readers and development tools','Automatic runtime enforcement of every type','Faster loops','Database storage'],0,'Type hints communicate intended types and help tools.'),
('Where can a return type be written?',['After the parameter list with ->','Before def only','Inside the function body','After return'],0,'The -> annotation specifies the return type.'),
('What is a docstring?',['A string describing a module, function, or class','A comment that Python ignores completely in all contexts','A database query','A decorator'],0,'Docstrings document program objects.'),
('Do type hints replace input validation?',['No','Yes','Only for strings','Only for lists'],0,'Untrusted runtime data still needs validation or conversion.'),
('What makes documentation useful?',['It explains behavior, inputs, outputs, and important constraints','It repeats the function name','It contains every implementation detail','It replaces tests'],0,'Useful documentation answers how to use the code and what it guarantees.')]),
('l23','HTTP APIs','APIs let Python programs exchange data with other services. The important skill is understanding requests, responses, status codes, JSON, and failure handling.','Understand HTTP requests and responses and design API code that handles failure explicitly.','An HTTP API exposes endpoints that clients can call. A response includes a status code and often structured data such as JSON.','The PyPath browser runtime may restrict network access. Treat live API calls as environment-dependent and understand the code even when a service cannot be reached.',['Explain request/response flow.','Recognize common status-code categories.','Parse JSON responses.','Handle timeouts and non-success responses.'],[('1. Request: A client asks an endpoint for a resource.','GET /users/42'),('2. Response: The server returns status and data.','200 OK + JSON'),('3. Check: Do not assume success.','if response.status_code != 200: ...'),('4. Parse: Convert JSON response data into Python structures.','data = response.json()')],
[('Do not assume every HTTP request succeeds.','Check status and handle expected failures.','if response.status_code >= 400: ...'),('Do not hard-code secrets into source code.','Use environment/configuration mechanisms outside the code.','API_KEY = os.environ.get("API_KEY")')],
'Inspect a sample API response represented as a Python dictionary and write code that handles a missing field safely. Live network calls may depend on the runtime.',
[('Guided','Identify method, endpoint, status code, and JSON body in a sample response.'),('Independent','Write a function that extracts a user name from a response dictionary safely.'),('Challenge','Design error handling for timeout, 404, 500, and invalid JSON cases.')],
[
('What does HTTP 200 usually indicate?',['A successful request','A client error','A server error','A redirect only'],0,'2xx status codes indicate success.'),
('What does a 404 mean?',['The requested resource was not found','The server succeeded','The request timed out','The client authenticated'],0,'404 is a client-side request for a resource that was not found.'),
('Why check a response status?',['The request can fail even when Python itself runs correctly','It makes JSON smaller','It creates a database','It avoids all network latency'],0,'Network and server failures are normal possibilities.'),
('Where should API secrets live?',['Outside source code, such as environment/configuration','Inside a public repository','In a print statement','In a quiz answer'],0,'Secrets should not be committed to source control.'),
('Why can an API example fail in PyPath even if the code is correct?',['The browser runtime may restrict network access','Python cannot use dictionaries','JSON is invalid Python','HTTP only works with classes'],0,'Browser sandbox/network restrictions can affect live requests.')]),
('l24','SQLite & SQL','Databases are useful when data becomes structured, searchable, and persistent. SQL teaches a different way to ask for data than ordinary Python loops.','Understand tables, rows, primary keys, SELECT, INSERT, UPDATE, DELETE, and parameterized SQL.','SQLite is an embedded database. SQL describes operations on tables and rows, while Python can use a database connection to execute those operations.','PyPath’s browser Python runtime may not include sqlite3 in every deployment. Learn the SQL model here and use the code in a compatible Python environment when the browser runtime cannot load SQLite.',['Explain table/row/column concepts.','Write basic SELECT/INSERT/UPDATE/DELETE statements.','Use parameters instead of string-built SQL.','Understand why databases differ from JSON files.'],[('1. Model: A table contains rows with named columns.','CREATE TABLE tasks (id INTEGER PRIMARY KEY, title TEXT)'),('2. Insert: Add a row.','INSERT INTO tasks (title) VALUES (?)'),('3. Query: Retrieve rows.','SELECT id, title FROM tasks'),('4. Parameterize: Bind values instead of concatenating SQL.','cursor.execute(sql, (title,))')],
[('Do not build SQL with string concatenation from user input.','Use parameterized queries.','cursor.execute("SELECT ... WHERE name = ?", (name,))'),('Do not treat SQLite as a drop-in replacement for every file.','Use a database when querying structured relationships matters.','SELECT ... WHERE ...')],
'Design a small tasks table and write the SQL needed to insert, list, complete, and delete tasks. Use parameter placeholders. Browser SQLite support may vary.',
[('Guided','Label the table, columns, and primary key in a sample schema.'),('Independent','Write CREATE TABLE and basic CRUD SQL for tasks.'),('Challenge','Design a query that lists incomplete tasks ordered by id and explain why parameterization matters.')],
[
('What is a row?',['One record in a table','A database file','A SQL keyword','A Python loop'],0,'Rows represent records.'),
('What does SELECT do?',['Retrieves data','Adds a row','Deletes a table','Starts Python'],0,'SELECT queries data.'),
('Why use parameterized SQL?',['It separates data from SQL syntax and helps prevent injection','It makes SQL longer','It disables indexes','It replaces tables'],0,'Parameters safely bind values into SQL statements.'),
('When is SQLite useful?',['For structured persistent data and queries','Only for printing','Only for HTTP','Never in Python'],0,'SQLite is useful for local structured data.'),
('Why might sqlite3 fail in PyPath?',['The browser Python runtime may not bundle that module','SQL syntax is never supported','Python cannot store data','Dictionaries are required'],0,'The runtime environment may not include sqlite3.')]),
('l25','Asyncio','Asynchronous programming helps a program make progress while it is waiting on tasks such as network operations. It is useful, but it is not a faster replacement for every loop.','Understand async/await, coroutines, and when concurrency helps.','asyncio provides cooperative concurrency. async defines a coroutine and await pauses it while another task can make progress.','Use asyncio for I/O-bound concurrency when the libraries involved support it. Ordinary synchronous code is often simpler for small scripts.',['Define async functions.','Use await correctly.','Understand coroutine versus normal function.','Recognize I/O-bound versus CPU-bound work.'],[('1. Define: Mark a coroutine with async def.','async def fetch(): ...'),('2. Await: Pause for an asynchronous operation.','result = await fetch()'),('3. Schedule: Multiple tasks can overlap waiting time.','tasks = [asyncio.create_task(fetch())]'),('4. Choose: CPU-heavy work usually needs a different strategy.','asyncio is not a magic CPU speedup.')],
[('Do not use async just because it is modern.','Use it when concurrency solves a real waiting problem.','async def fetch_data(): ...'),('Do not call async functions like normal functions and expect the result.','Await them in an async context.','result = await fetch_data()')],
'Write a small async example with two coroutines that sleep for different durations, then observe that their waiting periods can overlap.',
[('Guided','Identify which parts of a program are I/O-bound.'),('Independent','Write one async function using asyncio.sleep().' ),('Challenge','Run two simulated I/O tasks concurrently and compare the flow with sequential waiting.')],
[
('What does await do?',['Waits for an asynchronous result while allowing other async work to run','Creates a thread automatically','Makes CPU code faster','Stops Python'],0,'await suspends the current coroutine until the awaited operation completes.'),
('What does async def create?',['A coroutine function','A database','A thread','A generator only'],0,'async def defines a coroutine function.'),
('When is asyncio most useful?',['I/O-bound concurrent work','Heavy CPU calculations by themselves','Printing one line','Renaming variables'],0,'Asyncio is designed for cooperative I/O concurrency.'),
('Is asyncio always faster?',['No','Yes','Only for integers','Only on Windows'],0,'Concurrency adds complexity and helps only for suitable workloads.'),
('Why can two sleeps overlap in asyncio?',['While one coroutine waits, another can run','sleep removes the delay','Python skips the tasks','They are converted to threads'],0,'The event loop can run other ready coroutines during the wait.')]),
('l26','Logging & Configuration','Print statements are useful while learning, but real applications need structured diagnostic messages and configuration that can change without editing code.','Use logging levels and simple configuration patterns appropriately.','Logging records structured runtime information such as debug, info, warning, and error messages. Configuration separates changeable settings from program logic.','Log useful events and failures without leaking secrets or overwhelming the output.',['Use logging instead of scattered debug prints.','Choose levels deliberately.','Keep configuration separate from core logic.','Never log passwords or secret tokens.'],[('1. Configure: Choose a logging level and format.','logging.basicConfig(level=logging.INFO)'),('2. Record: Log meaningful events.','logging.info("Loaded %s tasks", count)'),('3. Warn: Record unusual but recoverable states.','logging.warning("Using default settings")'),('4. Protect: Keep secrets out of logs.','logging.error("Request failed")  # without API keys')],
[('Do not log passwords, tokens, or sensitive data.','Log safe context instead.','logging.info("User login attempted")'),('Do not use logging as a substitute for clear errors.','Raise or handle exceptions appropriately.','except ValueError:\n    logging.warning("Invalid age")')],
'Configure a logger and record a normal startup message, a warning for missing configuration, and an error for a failed operation without exposing secrets.',
[('Guided','Add info and warning log messages to a small script.'),('Independent','Replace three debug print statements with logging.'),('Challenge','Design a configuration object that supplies a file path and log level without hard-coding them in the business logic.')],
[
('Why use logging?',['To record useful runtime events with levels and context','Only to print faster','To replace functions','To store database rows'],0,'Logging provides structured runtime diagnostics.'),
('Which level usually signals a problem that needs attention but may be recoverable?',['WARNING','DEBUG','INFO','TRACE'],0,'WARNING is intended for unusual conditions that may need attention.'),
('What should never be logged casually?',['Passwords and secret tokens','A task count','A safe status message','A filename'],0,'Secrets can leak through logs.'),
('Why separate configuration?',['Settings can change without rewriting core logic','It makes code asynchronous','It removes tests','It forces global variables'],0,'Separating configuration improves maintainability.'),
('What is a good logging message?',['A useful event with safe context','A full password','A vague “something happened” only','An entire database dump'],0,'Logs should help diagnose behavior without leaking sensitive data.')]),
('l27','CLI, Git & Packaging','A real Python project needs a usable command-line interface, version history, and a repeatable way to organize and distribute code.','Build a simple CLI, understand essential Git commands, and recognize Python packaging concepts.','A CLI gives users commands and arguments. Git tracks project history. Packaging defines how Python code is structured and installed.','These are professional workflow skills: the goal is not memorizing every Git or packaging option, but understanding the normal development loop.',['Use argparse at a basic level.','Understand add/commit/status/log/push/pull in Git.','Explain a package and pyproject.toml at a high level.','Keep source and project metadata organized.'],[('1. CLI: Turn arguments into program inputs.','parser.add_argument("--name")'),('2. Track: Save a meaningful change in Git.','git add .\ngit commit -m "Add task filtering"'),('3. Inspect: Check project history and state.','git status\ngit log --oneline'),('4. Package: Describe a project for tools.','pyproject.toml')],
[('Do not make giant commits with unrelated changes.','Commit one coherent change at a time.','git commit -m "Add task filtering"'),('Do not commit secrets or generated clutter.','Use .gitignore and environment/configuration practices.','*.env\n__pycache__/')],
'Plan a small CLI command and write the Git commands you would use to record that feature safely. You do not need a remote repository to practice the workflow.',
[('Guided','Identify what each of git status, add, commit, and log tells you.'),('Independent','Design an argparse CLI with one required command and one optional flag.'),('Challenge','Write a clean commit sequence for adding a feature, fixing a bug, and documenting the change.')],
[
('What does git status show?',['The current working-tree state','Python output','Database rows','API responses'],0,'git status shows changed, staged, and untracked files.'),
('What does git commit do?',['Records staged changes in project history','Uploads every file automatically','Runs Python','Deletes the repository'],0,'A commit records staged changes locally.'),
('What is argparse useful for?',['Parsing command-line arguments','Writing SQL','Creating classes','Managing JSON'],0,'argparse builds command-line interfaces.'),
('Why use .gitignore?',['To keep unwanted/generated or secret files out of version control','To hide source code from Python','To delete history','To speed up loops'],0,'Gitignore prevents selected files from being tracked.'),
('What is pyproject.toml for?',['Project/build/tool configuration and metadata','Python bytecode','Only API secrets','A database table'],0,'pyproject.toml is a standard project configuration file.')]),
('l28','Architecture & Refactoring','As programs grow, structure becomes part of correctness. Refactoring means improving internal design without changing intended behavior.','Split responsibilities, reduce duplication, and refactor safely with tests as a safety net.','Architecture is the way responsibilities and dependencies are organized. Refactoring changes structure while preserving behavior.','Good architecture is not a complicated folder tree. Start with clear boundaries that make the program easier to change and test.',['Separate UI/input from business logic.','Keep functions and modules focused.','Refactor duplication into reusable code.','Use tests to protect behavior during changes.'],[('1. Separate: Keep user interaction away from core calculations.','get_input() -> calculate() -> show_result()'),('2. Extract: Move repeated behavior into one function.','def validate_age(value): ...'),('3. Refactor: Change structure without changing behavior.','old code -> helper function'),('4. Verify: Run tests after each meaningful refactor.','assert calculate_total(...) == expected')],
[('Do not refactor code that you do not understand.','First make the behavior clear and tested.','add tests before changing structure'),('Do not create abstractions for one tiny line.','Extract only when a repeated or meaningful responsibility exists.','def validate_input(...): ...')],
'Take a small program with input, calculation, and output in one function. Split it into focused functions without changing its behavior.',
[('Guided','Identify input, business logic, and output in a small script.'),('Independent','Split a mixed function into two or three focused functions.'),('Challenge','Remove one duplication, add a test, then refactor again while keeping all tests green.')],
[
('What is refactoring?',['Changing internal structure while preserving intended behavior','Adding random features','Deleting tests','Changing the requirements'],0,'Refactoring improves design without intentionally changing behavior.'),
('Why separate business logic from input/output?',['Core logic becomes easier to test and reuse','It makes programs asynchronous','It removes all bugs','It is required by Python'],0,'Pure core logic is easier to test and reuse.'),
('What is a useful reason to extract a function?',['A repeated or meaningful responsibility needs a name','Every line must become a function','To make files longer','To avoid variables'],0,'Abstractions should represent meaningful responsibilities.'),
('What protects behavior during refactoring?',['Focused tests','Long comments only','More global variables','Copying code'],0,'Tests provide evidence that behavior still works.'),
('What is good architecture?',['Clear responsibilities and dependencies that fit the problem','The most folders possible','The longest code','No functions'],0,'Architecture should make change and understanding easier.')]),
('l29','Performance & Practical Optimization','Fast code matters when performance is actually a problem. Professional Python starts with correct, measurable code and then improves the bottleneck rather than guessing.','Understand basic complexity, choose suitable data structures, measure before optimizing, and recognize common performance traps.','Performance is how efficiently a program uses time and memory. Optimization should be guided by measurement and the actual workload.','Correctness and clarity come first. Learn a few high-value ideas such as set membership, avoiding repeated work, and profiling before reaching for complex tricks.',['Recognize common O(n) versus O(1)-average membership patterns.','Use sets/dictionaries for frequent membership or lookup.','Avoid repeated expensive work inside loops.','Measure before and after an optimization.'],[('1. Notice: A list membership check scans items.','item in large_list'),('2. Choose: A set is usually better for repeated membership.','item in large_set'),('3. Avoid: Do not recompute the same expensive value.','cached = expensive()'),('4. Measure: Compare real timings before claiming improvement.','time.perf_counter()')],
[('Do not optimize code you have not measured.','Find the actual bottleneck first.','start = time.perf_counter()'),('Do not sacrifice clarity for tiny gains.','Choose the simpler data structure that meets the need.','seen = set(items)')],
'Compare membership checks using a list and a set, then explain which one is appropriate when the program performs many lookups.',
[('Guided','Identify which of five operations are likely repeated scans.'),('Independent','Replace repeated list membership checks with a set.'),('Challenge','Measure two approaches on a sample dataset and write a short conclusion.')],
[
('What should come before optimization?',['Correctness and measurement','Random code changes','More abstractions','Removing tests'],0,'You need correct behavior and evidence of a bottleneck.'),
('Why can a set help repeated membership checks?',['Set membership is designed for fast average lookup','Sets always use less memory','Sets sort automatically','Lists cannot use in'],0,'Sets are optimized for membership operations on unique values.'),
('What is a bottleneck?',['The part of a program consuming disproportionate resources','A syntax error','A variable name','A package file'],0,'A bottleneck limits overall performance.'),
('Why use time.perf_counter()?',['To measure elapsed time for code','To create a timestamped file only','To replace logging','To parse JSON'],0,'It provides a high-resolution performance timer.'),
('Which is the best optimization principle?',['Measure, change one thing, and measure again','Make everything shorter','Use async everywhere','Remove validation'],0,'Evidence-driven optimization reduces unnecessary complexity.')]),
('l30','Build, Test & Ship','The final step is integration: turn your Python knowledge into a maintainable program, verify it, document it, and explain your design.','Combine core Python skills into a small application and demonstrate that you can plan, build, test, debug, document, and ship it.','A finished program is more than code that runs once. It should meet a clear requirement, handle realistic input, be tested, understandable, and ready for another person to use.','Use this lesson as a practical skills check before the final project. You should be able to solve a small problem without following a full tutorial step by step.',['Turn requirements into a small plan.','Build with functions and appropriate data structures.','Validate input and handle expected errors.','Write tests for important behavior.','Document how to run and use the program.'],[('1. Plan: Define requirements and a small feature list.','Requirement: add, list, complete tasks'),('2. Build: Implement one behavior at a time.','add_task(title)'),('3. Verify: Test normal, edge, and invalid cases.','assert add_task("") is False'),('4. Ship: Explain setup, usage, and known limitations.','README: install -> run -> test')],
[('Do not call a program finished because it ran once.','Verify behavior with tests and realistic cases.','python -m unittest'),('Do not copy the final project solution.','Use the specification and your own design first.','Write the feature list before coding.')],
'Final skills check: build a small command-line program that accepts input, validates it, stores data in a list or dictionary, uses at least two functions, handles an expected error, and includes three assertions for core behavior.',
[('Guided','Turn a short specification into inputs, outputs, data, and functions.'),('Independent','Build the skills-check program without copying a complete solution.'),('Challenge','Refactor it into modules, add logging, document it, and explain one design decision.')],
[
('What should you do before building the final program?',['Define requirements and a small plan','Copy a large solution','Optimize first','Choose a framework'],0,'A small plan turns a vague problem into implementable behavior.'),
('What makes a program trustworthy?',['Tests plus handling of realistic and invalid cases','One successful run','Long code','Many comments only'],0,'Evidence and error handling improve confidence.'),
('What should the README explain?',['How to install, run, test, and use the program','Every Python keyword','Only the author name','Nothing'],0,'A useful README lets another person use the project.'),
('What should you do when debugging the final project?',['Use evidence, isolate the problem, change one thing, and rerun','Rewrite everything','Ignore the traceback','Disable tests'],0,'The same disciplined debugging process applies to larger programs.'),
('What does completing PyPath realistically demonstrate?',['A strong Python foundation and the ability to build small real programs','Professional mastery of every Python field','Knowledge of every library','Guaranteed employment'],0,'The course builds a foundation; specialization and experience continue beyond it.')])
]

# Apply core fields while preserving existing working code where possible.
for row in meta:
    lid,title,summary,intro,definition,why,skills,how,dodont,practice,levels,quiz=row
    x=by[lid]
    x['title']=title
    x['summary']=summary
    x['intro']=intro
    x['definition']=definition
    x['whyItMatters']=why
    x['skills']=skills
    x['howItWorks']=how
    x['doDont']=[{'do':a,'dont':b,'example':c} for a,b,c in dodont]
    x['practiceTask']=practice
    x['practiceLevels']=[{'level':a,'task':b} for a,b in levels]
    x['quiz']=[{'question':q,'options':opts,'answer':ans,'explanation':exp} for q,opts,ans,exp in quiz]
    x['quickInfo']=[['Goal', 'Build understanding you can use in code.'], ['Practice', 'Guided → Independent → Challenge']]
    x['advancedNote'] = lid in {'l20','l21','l22','l25','l26','l27','l28','l29'}
    if lid in {'l23','l24'}:
        x['runtimeNote']='This topic may depend on the Python runtime available in your browser. If the live environment cannot provide network access or sqlite3, use the lesson examples to understand the concept and run the same code in a full local Python environment.'
    else:
        x.pop('runtimeNote',None)

# Reorder the conceptual focus without changing IDs, preserving 30 lesson checkpoints.
# IDs and day numbers remain stable for saved progress and navigation.
for i in range(30):
    by[f'l{i+1:02d}']['day']=i+1
    by[f'l{i+1:02d}']['number']=i+1

# Keep projects at their existing checkpoints and strengthen their project-learning loop.
projects=[x for x in data if x['kind']=='project']
for p in projects:
    p['howItWorks']=[
        '1. Requirements: write the features and success conditions before coding.',
        '2. Plan: break the project into the smallest useful behaviors.',
        '3. Guided build: implement one behavior, run it, and inspect the result.',
        '4. Independent build: complete the next behavior without copying the full solution.',
        '5. Debug & test: check normal, boundary, and invalid cases.',
        '6. Review: improve one name, structure, or repeated section after tests pass.'
    ]
    p['practiceLevels']=[
        {'level':'Guided','task':'Implement the first required behavior using the starter structure, then run it.'},
        {'level':'Independent','task':'Build the next feature from the requirements without opening the complete solution first.'},
        {'level':'Challenge','task':'Add one useful improvement, then test an edge case and explain your design choice.'}
    ]
    p['whyItMatters']='Projects turn isolated Python concepts into a complete program. The goal is to practice planning, building, testing, debugging, and reviewing rather than copying a finished answer.'
    p['skills']=[
        'Break requirements into small features.',
        'Reuse earlier Python concepts instead of starting from scratch.',
        'Handle normal, invalid, and edge cases.',
        'Test the important behavior before calling the project finished.'
    ]
    p['quickInfo']=[['Build loop','Plan → Build → Run → Debug → Test → Review'],['Rule','Use the complete example as a reference, not as the first step.']]
    p['quiz']=[
        {'question':'What should you do before coding the project?','options':['Write requirements and a small plan','Copy the full solution','Add every feature at once','Skip testing'],'answer':0,'explanation':'A short plan makes the project concrete and gives you a sequence of small behaviors to implement.'},
        {'question':'What is the best build rhythm?','options':['One behavior at a time, then run and inspect it','Write everything before running','Only code after reading the answer','Never test until the end'],'answer':0,'explanation':'Small increments make mistakes easier to locate and give you fast feedback.'},
        {'question':'Which testing set is strongest?','options':['Normal, boundary, and invalid cases','Only one successful case','Only visual checks','No tests'],'answer':0,'explanation':'Different input classes expose different bugs.'},
        {'question':'What is a good debugging habit?','options':['Use evidence, change one thing, and rerun','Rewrite the entire project','Ignore the error','Change many unrelated lines'],'answer':0,'explanation':'Evidence-based, small changes preserve your understanding of cause and effect.'},
        {'question':'When is the project ready to review?','options':['When it works, is tested, and you can explain the design','When it runs once','When it has the most code','When the reference answer is copied'],'answer':0,'explanation':'A working program still needs evidence and understandable design.'}
    ]

# Make final project description explicitly a learner-owned application, while retaining its working code.
p5=by['p05']
p5['summary']='Build your own small maintainable Python application from a specification, then test, document, and review it.'
p5['definition']='The final project is an integration challenge. Choose a practical command-line application, design it yourself, and demonstrate that you can combine Python fundamentals with validation, persistence, testing, structure, and documentation.'
p5['outcome']='A small maintainable command-line application that you can explain, test, and run yourself.'
p5['bio']='A final integration project where you turn a clear specification into your own application instead of following a complete tutorial solution. The reference code remains available as a review example.'
p5['practiceTask']='Final project: choose a practical CLI app, write its requirements, build the core behavior yourself, test normal and invalid cases, document how to run it, and explain one design decision.'
p5['tags']=['Python','Functions','Validation','Persistence','Testing','CLI','Refactoring']
p5['difficulty']='Advanced'
p5['classFrom']=25
p5['afterLesson']=30

# Ensure all lessons have the new teaching fields, while preserving project semantics.
for x in data:
    if x['kind']=='lesson':
        x.pop('teachingPoints', None)
        # Keep complete examples intact; ensure a starter exists.
        if not x.get('starterCode'):
            x['starterCode']=x['fullExample']

path=Path('/tmp/pypath/src/data/lessons.json')
path.write_text(json.dumps(data, indent=2, ensure_ascii=False)+'\n')
